# Generated by Django 4.2.7 on 2023-11-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=200)),
                ('L_Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
